package com.marcoabreu.att.communication;

/**
 * Created by AbreuM on 02.08.2016.
 */
public enum Opcode {
    PAIR_REQUEST,
    PAIR_RESPONSE,
    ABORT_ACTION_REQUEST,
    EXECUTE_ACTION_REQUEST,
    EXECUTE_ACTION_RESPONSE,
    STORAGE_DATA_GET_REQUEST,
    STORAGE_DATA_GET_RESPONSE,
    STORAGE_DATA_SAVE_REQUEST,
    STORAGE_DATA_SAVE_RESPONSE,
    COMPILER_DEX_REQUEST,
    COMPILER_DEX_RESPONSE,

    TEST
}
